services:
  app:
    image: picrew-bot
    build: .
    restart: unless-stopped
    volumes:
      - ./state:/app/state
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
      FONT_PATH: /usr/share/fonts/truetype/noto/NotoSansMono-Bold.ttf
    dns:
      - 1.1.1.1
